### ISSUE TITLE
Decomposition Comparison

### ISSUE THREAD

**Issue by SamyAteia** [pragmalingu/pragmalingu#48]

**Comment by SamyAteia** [comment]
Basic Layout (Article):

- [ ] Add discussion section to Private notebook for finding discussion relevant examples.

- [ ] Introduction, what, why
        What: Decomposition what is it?
        Why: What is the benefit. Formulate Hypothesis
- [ ]  How -> Explain steps taken in private notebook, Example for Translation 
- [ ]  Results, Pictures
- [ ]  Discussion: What are interesting results (unexpected with our hypothesis).

Discussion Ideas for decomposition experiment:

(Interessante Ergebnisse)

Warum ist Lisa, Cranfield, ADI, stemming besser als Kompositazerlegung. ADI ist Teil von LISA, -> Nur LISA und Cranfield anschauen.

Medline, warum funktioniert der brute force decomposer bei medline besser als der hyphenation decompounder?

NPL -> stärkste False Negatives bei stemmer vs hyphenation decompounder anschauen und schöne Beispiele für den vorteil von Kompositazerlegung heraussuchen.

NPL -> Unterschied zwischen hyphenation decompounder und brute-force decompounder anschauen.

Warum ist Englisch multi match query deutlich besser als deutsch?

Time, warum gibt es keinen unterschied beim einsatz des german analyzers vs. multimatch.

Vergleich von englischer Multi-Match Query mit deutscher Multi Match Query. Warum ist deutsch soviel schlechter.

**Comment by MiriamRupprecht** [comment]
Done writing the article. Waiting for review
