### ISSUE TITLE
Decomposition Review

### ISSUE THREAD

**Issue by SamyAteia** [pragmalingu/pragmalingu#52]
- [x] Check cut off labels on svgs

- [x] Missing axes labels for term plots 
- [x] Label alignment for term plots (Add fieldname: prefix? to label?) text_german: bibliothek, ...
- [x] Better sub headlines (size to big) -> hashtag, maybe check css overrides for docusaurus, 
- [x] Add Conclusion section? -> Maybe later if we have content
- [x] idf infobox only ones? -> Keep infoboxes for skipping readers

**Comment by SamyAteia** [comment]
- [ ] Check cut off labels on svgs
- [ ] Missing axes labels for term plots
- [ ] Label alignment for term plots
- [ ] Better sub headlines (size to big)

**Comment by MiriamRupprecht** [comment]
Fix everything, waiting for review before I close this Issue
